### ISSUE TITLE
[MAJOR ISSUE] Satillite texture not compatible with 1.7.10. [PLEASE FIX IMMEDIATELY]

### ISSUE THREAD

**Issue by ghost** [mMONTAGEe-Workshop/GalactiCircle#2]
The reason this is a Major Issue, is because i'm trying to retexture the Space Station for my Modpack, in 1.7.10 with Galaxy Space as a Planet Ring. And my Modpack and everything I created will compleatly fail if the Space Station texture is not compatible with 1.7.10. PLEASE! add full compatibility with 1.7.10!!!! I DON'T WANT TO HAVE TO THROW AWAY MY INTIRE CREATION!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
![Screenshot 2024-05-07 141052](https://github.com/mMONTAGEe-Workshop/GalactiCircle/assets/166317640/5a04351c-d11b-40fb-965f-1c977ed42196)

**Comment by ghost** [comment]
I had to use your Pack as a base for custom Texture Packs. I'm kind of a noob at creating texture packs. I'm trying to create a texture pack that retextures Earth as Saturn. Thanks to the Gas Giants in Galaxy Space not being directly accesable. I won't try to sell it. This pack is just for myself.

**Comment by ghost** [comment]
I made GalactiCircle compatible with ExtraPlanets. And it is very cool looking.

**Comment by mMONTAGEe** [comment]
could you please rephrase and in details explain whats your issue, i don't quite understand it, and next time even in sarcastic tone do not demand from me anything, i will try when i can
