### ISSUE TITLE
[BUG] Texture not compatible with Neptune.

### ISSUE THREAD

**Issue by ghost** [mMONTAGEe-Workshop/GalactiCircle#3]
If Galaxy Space is not installed, neptune will retain a square shape. 
![Uploading Screenshot 2024-05-08 174114.png…]()

**Comment by ghost** [comment]
Screenshot uploader broken.

**Comment by mMONTAGEe** [comment]
doesn't seem like to be absence of the texture without galaxy space, are you sure you don't have any mods installed that modify solar system such as Extra Planets?

**Comment by ghost** [comment]
I made extra planets compatible.
