### ISSUE TITLE
[BUG] Neptune on Triton skybox, is compleatly square.

### ISSUE THREAD

**Issue by ghost** [mMONTAGEe-Workshop/GalactiCircle#4]
![Screenshot 2024-05-23 171636](https://github.com/mMONTAGEe-Workshop/GalactiCircle/assets/166317640/aa3b750e-e44b-4c92-8ee8-21c20fabda2c)

**Comment by ghost** [comment]
EULA

1 Bumping Threads Is Not Allowed.

2 You Will Be BANNED, If One Rules Is Broken.

3 Be A Robot, Emotiones Are Not Allowed On This ISSUE.

**Comment by mMONTAGEe** [comment]
Something to do with GalaxySpace, unsure how to resolve this
