### ISSUE TITLE
[FETURE REQUEST] Add Additional Planets compatibility.

### ISSUE THREAD

**Issue by ghost** [mMONTAGEe-Workshop/GalactiCircle#5]
![637879774643436283](https://github.com/mMONTAGEe-Workshop/GalactiCircle/assets/166317640/400ba7d0-7d6c-4ead-9df9-8de35cac5f50)

**Comment by mMONTAGEe** [comment]
No such thing exists, i think you mean Extra Planets in which case no, i really not fan of that addon
