### ISSUE TITLE
[BUG]GalactiCircle2.0 texture wrong

### ISSUE THREAD

**Issue by senfun** [mMONTAGEe-Workshop/GalactiCircle#6]
sorry my english is bad.
when i use GalactiCircle2.0 in my modpack.
my Draconic Evolution mod texture are the wrong. 
version:Draconic-Evolution-1.12.2-2.3.28.354-universal
![texture wrong](https://github.com/mMONTAGEe-Workshop/GalactiCircle/assets/96683451/542f990d-243a-4f5c-8977-9facde453abc)

**Comment by mMONTAGEe** [comment]
GalactiCircle has nothing to do with Draconic Evolution

**Comment by mMONTAGEe** [comment]
Did the issue appear after installing the texture pack? and perhaps specifications on what exacly is wrong, im unfamiliar with Draconic Evolution

**Comment by senfun** [comment]
Sorry, it went back to normal when I restarted the game. Thank you for your response, and sorry for the inconvenience.
